### ISSUE TITLE
Hacktoberfest easy, readme.md needs formatting

### ISSUE THREAD

**Issue by pyropyro78** [pyropyro78/AdminDrop#2]
This should be a quick Hacktoberfest entry. The formatting would look better with tables or just something to make it look neater. This is not only to help you get an easy pull request by also to help make things easier to understand. Not picky on layout. If you want more easy requests look at any of my plugins and fix up their readme.md too. Happy hacking!
#hacktoberfest2019
#hacktoberfest

**Comment by PavanKKamra** [comment]
Hi, I would like to work on this request :)

**Comment by pyropyro78** [comment]
Have at it :) Thank you for the help

**Comment by pyropyro78** [comment]
Oh, as a note. You can leave the alt and normal command sections, I realize right now they are the same verbage. I will fix that after you, unless you want to look at the plugin.yml or the CommandHandlers.java file

**Comment by pyropyro78** [comment]
Issues resolved via merge with PavanKKamra's branch.
